### ISSUE TITLE
CachableFlash::Middleware not working

### ISSUE THREAD

**Issue by blim8183** [pboling/cacheable-flash#15]
I've tried swapping the Cacheable Flash middleware in using the instructions in the README but it doesn't seem to be working for me. Unfortunately, it's also not giving me any errors. Is there anything I need to do beyond adding "config.middleware.swap ActionDispatch::Flash, CacheableFlash::Middleware" to my application.rb?

**Comment by pboling** [comment]
Please consider switching to https://github.com/leonid-shevtsov/unobtrusive_flash
