### ISSUE TITLE
Using the middleware doesn't sweep the flash

### ISSUE THREAD

**Issue by ansel1** [pboling/cacheable-flash#29]
I tried using the middleware as documented (by replacing the ActionDispatch::Flash middleware with it).

I was getting my messages, but some messages were getting 'stuck' in session.  I think it's because if the ActionDispatch::Flash middleware doesn't run, the Flash object never gets swept.  The rack environment contains two copies of the FlashHash: one under a flash key, and another copy serialized into the session cookie.  The one in the session cookie never dies, and the messages are never swept.

I found that by using `config.middleware.insert_before ActionDispatch::Flash, CacheableFlash::Middleware` (instead of `swap`), everything works as expected.

**Comment by pboling** [comment]
Please consider switching to https://github.com/leonid-shevtsov/unobtrusive_flash
