### ISSUE TITLE
Make flash_cookie helper be an instance of HashWithIndifferentAccess

### ISSUE THREAD

**Issue by petRUShka** [pboling/cacheable-flash#34]
Now I should write `flash_cookie["notice"]` but `flash[:notice]` that isn't convinient. 

So solution is to use [HashWithIndifferentAccess](http://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html) instead of regular flash.

**Comment by pboling** [comment]
Please consider switching to https://github.com/leonid-shevtsov/unobtrusive_flash
