### ISSUE TITLE
Is cacheable-flash enabled?

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [pboling/cacheable-flash#40]
I would like to be able to tell whether or not cacheable-flash is active and working in my app.

I am transitioning from in-memory session storage to cookie-based storage of the flash object but I don't necessarily want to delete my old code. I would rather have both options available. In the future for other reasons I may transition back to serving flash messages inside the HTML directly.

Something like `CacheableFlash.active?` which is set to true when the middleware is used or when included in a controller. I'd rather not simply detect the presence of the `CacheableFlash` constant is it may be included but not used.

**Comment by JakeTheSnake3p0** [comment]
Also, I noticed that when I tried to explicitly set `Rails.application.config.session_store` to `ActionDispatch::Session::CacheStore`, rails still has `ActionDispatch::Session::CookieStore` set. Does this gem override whatever default is set?

**Comment by pboling** [comment]
That would be a useful tool to have.  I don't have much time to work on this gem anymore myself, and would appreciate any help you can render.  I will look into the session store override issue.

**Comment by pboling** [comment]
I can't find any code in this project that would override the session store.  However, this gem does require a cookie store, so perhaps something in Rails is being "too smart" about that?  You should stop including this in the application controller, and/or unload the middleware.  This code will not work at all without a cookie store set.
