### ISSUE TITLE
Cookie set even if flash is empty

### ISSUE THREAD

**Issue by thomassnielsen** [pboling/cacheable-flash#45]
I get `Set-Cookie:flash=%7B%7D; path=/` with every request, which breaks caching. Using rails 4.1. We're using cacheable-flash as middleware.

**Comment by pboling** [comment]
No maintainer of this gem is currently using it.  PRs are welcome, and new maintainers too!

**Comment by pboling** [comment]
Please consider switching to https://github.com/leonid-shevtsov/unobtrusive_flash
