### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by fredngo** [pboling/cacheable-flash#52]
I've tried my best to get cacheable-flash working with Rails 5, and I even fixed up its sister gem [stackable_flash](https://github.com/pboling/stackable_flash) with a [PR](https://github.com/pboling/stackable_flash/pull/7) so that it could be used in Rails 5.1 without deprecation errors, but in the end the flash messages are behaving erratically in Rails 5 and I was unable to solve the problems.

My best guess right now is that `ActionDispatch::Flash` has changed too much; there were quite a lot of changes between Rails 4 and 5 on how flashes are handled, especially how flashes are swept between requests.

Luckily, with some minor changes to my app, [unobtrusive_flash](https://github.com/leonid-shevtsov/unobtrusive_flash) is a viable replacement, and seems to work well on Rails 5.

Thanks Peter for this gem, it was really nice to have been able to use it all these years. If you've moved on and are no longer maintaining this gem; I'd suggest pointing folks towards [unobtrusive_flash](https://github.com/leonid-shevtsov/unobtrusive_flash).

Still working perfectly on Rails 4 for projects that do not need to upgrade.

**Comment by pboling** [comment]
I no longer have time to do a lot of maintenance on this gem.  I have mostly been accommodating the work others are doing, reviewing, merging and releasing.

Would be happy to find other maintainers, and also to point people to `unobtrusive_flash`

**Comment by pboling** [comment]
Added https://github.com/leonid-shevtsov/unobtrusive_flash to Readme.
